name: JeremyHughes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#cecece'
    - '#5a5a5a'
    - '#8a8a8a'
  brandStrength: 1
  lightness: 0.32227300526574254
  saturation: 0.5160885583609343
  rhythmicContrast: 0
purpose: []
